function drawVerityGrid(random){const symbols=['cherry','gem','crown','bell','clover'];return Array.from({length:5},(_,column)=>Array.from({length:3},()=>{const value=random();if(value<.01)return 'smile';if(value<.61)return symbols[column];const others=symbols.filter((_,i)=>i!==column);return others[Math.min(3,Math.floor((value-.61)/.39*4))]}))}
function evaluateVerityConnected(grid){let best={multi:0,line:null,symbol:null,count:0};const targets=['cherry','gem','crown','bell','clover'];for(const target of targets){function walk(column,row,path){if(column>=5)return;const value=grid[column][row];if(value!==target&&value!=='smile')return;const next=path.concat(row),count=next.length,multi=count>=5?10:count===4?4:count===3?1.5:0;if(multi>best.multi)best={multi,line:next,symbol:target,count};for(let r=Math.max(0,row-1);r<=Math.min(2,row+1);r++)walk(column+1,r,next)}for(let row=0;row<3;row++)walk(0,row,[])}return best}
function evaluateVerity(grid,pays=[4,12,40]){let best={multi:0,line:null,symbol:null,count:0};const lines=[[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2]];for(const line of lines){const symbols=line.map((r,c)=>grid[c][r]);const target=symbols.find(s=>s!=='smile')||'smile';let count=0;for(const s of symbols){if(s===target||s==='smile')count++;else break}const multi=count>=5?pays[2]:count===4?pays[1]:count===3?pays[0]:0;if(multi>best.multi)best={multi,line,symbol:target,count}}return best}

// Deterministic outcomes shared by the Worker and browser round engine.
function seeded(seed){let v=seed>>>0;return()=>{v=(Math.imul(v,1664525)+1013904223)>>>0;return v/4294967296}}
function expected(game,seed,count=3){const random=seeded(seed);if(game==='aviator')return{crash:Math.min(200,Math.max(1.02,.97/Math.pow(1-random(),1.35)))};if(game==='double'){const values=[0,1,8,2,9,3,10,4,11,5,12,6,13,7,14],n=values[Math.floor(random()*15)];return{number:n,color:n===0?'gold':n<=7?'red':'black'}}if(game==='verite'){const grid=drawVerityGrid(random);return{symbols:grid.map(c=>c[1]),grid,...evaluateVerityConnected(grid)}}if(game==='mines'){const bombs=new Set;while(bombs.size<count)bombs.add(Math.floor(random()*25));return{bombs:[...bombs]}}if(game==='plinko'){const pins=[];for(let row=0;row<10;row++)for(let col=0;col<row+3;col++)pins.push({x:300+(col-(row+2)/2)*41,y:38+row*35});const b={x:300+(random()-.5)*20,y:8,vx:(random()-.5)*1.4,vy:.1};for(let frame=0;frame<30000;frame++){b.vy+=.12;b.vx*=.999;b.x+=b.vx;b.y+=b.vy;for(const p of pins){const dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy);if(d<12&&d>.001){const nx=dx/d,ny=dy/d;b.x=p.x+nx*12.1;b.y=p.y+ny*12.1;const dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=1.65*dot*nx;b.vy-=1.65*dot*ny;b.vx+=(random()-.5)*.3}if(Math.abs(b.vx)<.1&&dy<0)b.vx+=(random()<.5?-1:1)*.4}}if(b.x<15){b.x=15;b.vx=Math.abs(b.vx)*.8}if(b.x>585){b.x=585;b.vx=-Math.abs(b.vx)*.8}if(b.y>420){const bin=Math.max(0,Math.min(8,Math.floor(b.x/600*9)));return{bin,multi:[10,3,1,.5,.2,.5,1,3,10][bin]}}}throw Error('Physics did not settle')}throw Error('Unknown game')}

// Deterministic scenes and Plinko paths shared with the authenticated server.
function arcadeRandom(seed){let v=seed>>>0;return()=>{v=(Math.imul(v,1664525)+1013904223)>>>0;return v/4294967296;};}
const arcadePots=[12,3,1.2,.6,.35,.6,1.2,3,12];
const arcadeLadder=[0,.35,.6,.9,1.2,1.6,2.2,3,4.5];
function arcadeOutcome(game,seed,options={}){const r=arcadeRandom(seed);
 if(game==='plinko'){const count=[1,2,3].includes(options.balls)?options.balls:1,discount=count===1?1:count===2?.9:.8;const paths=Array.from({length:count},()=>Array.from({length:8},()=>r()<.5?0:1));const bins=paths.map(p=>p.reduce((a,b)=>a+b,0));return{paths,bins,balls:count,discount,multi:Math.round(bins.reduce((a,b)=>a+arcadePots[b],0)/count*discount*10000)/10000};}
 if(game==='mecha'){const mirror=!!(seed&1);const boxes=[[.105,.145,.052,.093],[.376,.106,.046,.067],[.608,.205,.033,.083],[.864,.123,.049,.081],[.171,.598,.042,.105],[.419,.665,.027,.117],[.658,.564,.044,.147],[.868,.714,.049,.101]];return{sceneSeed:seed,mirror,targets:boxes.map(([u,v,w,h],id)=>({id,u:mirror?1-u-w:u,v,w,h})),multi:0};}
 if(game==='sahur'){const names=['lantern','drum','dome','dates','parcel','moon','soup','book'];const grid=Array.from({length:5},()=>Array.from({length:3},()=>{const v=r();return v<.025?'wild':names[Math.min(7,Math.floor((v-.025)/.975*8))];}));let multi=0,line=null;for(const path of [[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2]]){const target=path.map((row,c)=>grid[c][row]).find(s=>s!=='wild')||'wild';let n=0;for(let c=0;c<5;c++){const s=grid[c][path[c]];if(s!==target&&s!=='wild')break;n++;}const pay=n>=5?18:n===4?6:n===3?2:0;if(pay>multi){multi=pay;line=path.slice(0,n);}}return{grid,multi,line};}
 if(game==='fishing'){const value=r(),fish=value<.36?0:value<.66?1:value<.84?2:value<.94?3:value<.99?4:5;return{fish,names:['Tilápia','Pargo','Atum','Peixe-vela','Arraia mística','Tesouro submerso'],multi:[.4,.75,1.2,2.2,4,7][fish],bite:2+r()*2,window:1.25};}
 throw Error('Jogo desconhecido');
}

const allowed=['aviator','verite','double','mines','plinko','mateo','pirate','bacbo','mecha','sahur','fishing'];
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Cache-Control':'no-store'};
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:cors});
const base=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
async function db(path:string,method='GET',body?:unknown){const r=await fetch(base+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.message||'Falha no banco');return data;}
const rpc=(name:string,body:unknown)=>db('rpc/'+name,'POST',body);
function slot(grid:string[][],pays:number[]){let multi=0;for(const line of [[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2]]){const symbols=line.map((r,c)=>grid[c][r]),target=symbols.find(s=>s!=='wild')||'wild';let count=0;for(const s of symbols){if(s===target||s==='wild')count++;else break;}multi=Math.max(multi,count>=5?pays[2]:count===4?pays[1]:count===3?pays[0]:0);}return {grid,multi};}
export function outcome(game:string,seed:number,options:any){if(['plinko','mecha','sahur','fishing'].includes(game))return arcadeOutcome(game,seed,options);const random=seeded(seed);if(game==='mateo'){const names=['wild','crown','bell','clover','gem','coins','flower','mushroom'];return slot(Array.from({length:5},()=>Array.from({length:3},()=>random()<.035?'wild':names[1+Math.floor(random()*7)])),[1.5,4,10]);}if(game==='pirate'){const names=['ice','magma','heart','treasure','skull','sword','coin','crown'];return slot(Array.from({length:5},()=>Array.from({length:3},()=>{const r=random();return r<.015?'wild':names[Math.min(7,Math.floor((r-.015)/.985*8))];})),[2,6,20]);}if(game==='bacbo'){for(let i=0;i<48;i++)random();const dice=Array.from({length:4},()=>1+Math.floor(random()*6)),p=dice[0]+dice[1],b=dice[2]+dice[3],side=p===b?'tie':p>b?'player':'bank';return{dice,multi:side===options.side?(side==='tie'?({2:89,3:26,4:11,5:7,6:5,7:5,8:5,9:7,10:11,11:26,12:89} as any)[p]:2):side==='tie'&&options.side!=='tie'?1:0};}const result=expected(game,seed,options.mines);if(game==='double')result.multi=(result.color===options.color||result.color==='gold'&&options.color==='yellow')?(result.color==='gold'?14:2):0;return result;}
function minesMulti(r:any){const opened=r.opened as number[];if(!opened.length||opened.some(i=>r.result.bombs.includes(i)))return 0;let probability=1;for(let j=0;j<opened.length;j++)probability*=(25-r.options.mines-j)/(25-j);return Math.min(1000,Math.round(.97/probability*100)/100);}
// Casual mode: increase ordinary wins without changing visual combinations or paying invented paths.
export function balancedOutcome(game:string,options:any,draw=()=>crypto.getRandomValues(new Uint32Array(1))[0]){let seed=draw(),result=outcome(game,seed,options);const boost=game==='aviator'?.42:game==='verite'?.12:game==='mateo'?.14:game==='pirate'?.14:game==='sahur'?.14:0;const good=(r:any)=>game==='aviator'?r.crash>=2:game==='plinko'?r.multi>=1:r.multi>0;const coin=draw()/4294967296;if(!good(result)&&coin<boost){for(let attempt=0;attempt<120;attempt++){const candidateSeed=draw(),candidate=outcome(game,candidateSeed,options);if(good(candidate)){seed=candidateSeed;result=candidate;break;}}}return {seed,result};}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors});try{if(req.method!=='POST')return reply({error:'Método inválido'},405);const token=req.headers.get('Authorization');if(!token)return reply({error:'Entre como convidado'},401);const auth=await fetch(base+'/auth/v1/user',{headers:{apikey:key,Authorization:token}});if(!auth.ok)return reply({error:'Sessão expirada. Entre novamente.'},401);const user=await auth.json(),id=user.id;const text=await req.text();if(text.length>300000)return reply({error:'Arquivo muito grande'},413);const body=JSON.parse(text),action=body.action;
const profiles=await db('bet_profiles?id=eq.'+id);if(!profiles.length)await db('bet_profiles','POST',{id,name:'Player',balance:50000});
if(action==='love')return reply(await rpc('bet_love',{p_user:id}));
if(action==='arcade/hit'){if(!/^[0-9a-f-]{36}$/i.test(body.round||''))throw Error('Rodada inválida');return reply(await rpc('bet_arcade_hit',{p_user:id,p_round:body.round,p_target:Number.isInteger(body.target)?body.target:-1,p_at:Math.min(Date.now(),Math.max(Date.now()-500,Number(body.at)||Date.now()))}));}
if(action==='bonus')return reply(await rpc('bet_bonus',{p_user:id}));
if(action==='duel/invite'){
 if(!['verite','mateo','pirate'].includes(body.game)||body.receiver===id||!/^[0-9a-f-]{36}$/i.test(body.receiver||''))throw Error('Convite inválido');
 const recent=await db('bet_duels?sender=eq.'+id+'&status=eq.pending&created=gte.'+new Date(Date.now()-600000).toISOString());if(recent.length>=3)throw Error('Aguarde seus convites pendentes');
 const rows=await db('bet_duels','POST',{sender:id,receiver:body.receiver,game:body.game});return reply({duel:rows[0].id});
}
if(['duel/accept','duel/status','duel/spin','duel/decline'].includes(action)){
 if(!/^[0-9a-f-]{36}$/i.test(body.id||''))throw Error('X1 inválido');
 let plans:any={};if(action==='duel/accept'){
  const d=(await db('bet_duels?id=eq.'+body.id+'&receiver=eq.'+id+'&status=eq.pending'))[0];if(!d)throw Error('Convite indisponível');
  for(const player of [d.sender,d.receiver])plans[player]=Array.from({length:15},()=>{const o=balancedOutcome(d.game,{});return{seed:o.seed,...o.result};});
 }
 return reply({...await rpc('bet_duel',{p_user:id,p_id:body.id,p_action:action.split('/')[1],p_plans:plans}),serverTime:Date.now()});
}
if(action==='state'){
 const active=await db('bet_duels?status=eq.active&or=(sender.eq.'+id+',receiver.eq.'+id+')&select=id');
 for(const d of active)await rpc('bet_duel',{p_user:id,p_id:d.id,p_action:'status'});
 const duels=await db('bet_duels?or=(sender.eq.'+id+',receiver.eq.'+id+')&select=id,sender,receiver,game,status,started,ends,created,winner,transfer&order=created.desc&limit=20');const [users,log,challenges,pending]=await Promise.all([db('bet_profiles?select=id,name,balance,photo,wins,rounds,bonus_at&order=balance.desc'),db('bet_events?user_id=eq.'+id+'&order=time.desc&limit=100'),db('bet_challenges?or=(sender.eq.'+id+',receiver.eq.'+id+')&order=created.desc&limit=50'),db('bet_rounds?user_id=eq.'+id+'&status=eq.open&select=id,game')]);return reply({engine:3,serverTime:Date.now(),duels,user:users.find((u:any)=>u.id===id),friends:users,log,challenges:challenges.map((c:any)=>({...c,sender_name:users.find((u:any)=>u.id===c.sender)?.name})),pending});}
if(action==='profile'){const name=String(body.name||'').trim();if(!name||name.length>24)throw Error('Use um apelido de 1 a 24 caracteres');const changes:any={name};if(body.removePhoto)changes.photo=null;if(body.photo){if(!/^data:image\/jpeg;base64,/.test(body.photo)||body.photo.length>250000)throw Error('Foto inválida');changes.photo=body.photo;}await db('bet_profiles?id=eq.'+id,'PATCH',changes);return reply({ok:true});}
if(action==='round'){if(!allowed.includes(body.game)||!Number.isSafeInteger(body.bet)||body.bet<100)throw Error('Aposta inválida');const options={balls:[1,2,3].includes(body.balls)?body.balls:1,color:['red','black','yellow'].includes(body.color)?body.color:'red',side:['player','bank','tie'].includes(body.side)?body.side:'player',mines:[2,3,4,5,8,10].includes(body.mines)?body.mines:2},{seed,result}=balancedOutcome(body.game,options);const round=await rpc('bet_begin',{p_user:id,p_game:body.game,p_bet:body.bet,p_seed:seed,p_options:options,p_result:result});return reply({...round,serverTime:Date.now(),engine:3,mines:options.mines,seed:['aviator','mines','fishing'].includes(body.game)?undefined:seed,arcade:body.game==='plinko'?result:body.game==='mecha'?{sceneSeed:seed,mirror:result.mirror,targets:result.targets}:body.game==='sahur'?result:body.game==='fishing'?{bite:result.bite,window:result.window}:undefined});}
if(['settle','reveal','flight','recover'].includes(action)){let round;if(action==='recover')round=(await db('bet_rounds?user_id=eq.'+id+'&status=eq.open'))[0];else{if(!/^[0-9a-f-]{36}$/i.test(body.round||''))throw Error('Rodada inválida');round=(await db('bet_rounds?id=eq.'+body.round+'&user_id=eq.'+id))[0];}if(!round)return reply({ok:true});const r=round;
if(action==='reveal'){if(!Number.isInteger(body.cell)||body.cell<0||body.cell>24)throw Error('Quadrado inválido');return reply(await rpc('bet_open_cell',{p_user:id,p_round:r.id,p_cell:body.cell}));}
const value=Math.pow(1.025,Math.floor(Math.max(0,Date.now()-Date.parse(r.created))/120));
if(action==='flight'){if(r.game!=='aviator')throw Error('Jogo inválido');return reply({value:Math.min(value,r.result.crash),ended:value>=r.result.crash,serverTime:Date.now(),created:r.created});}
let multi=r.result.multi||0;if(r.game==='mecha'){const p=r.progress||{},found=(p.found||[]).length;multi=action==='recover'||p.misses>=2||Date.now()-Date.parse(r.created)>60000?0:[0,.35,.6,.9,1.2,1.6,2.2,3,4.5][Math.min(8,found)];}if(r.game==='fishing'){const elapsed=(Date.now()-Date.parse(r.created))/1000;multi=action==='recover'||elapsed<r.result.bite||elapsed>r.result.bite+r.result.window?0:r.result.multi;}if(r.game==='mines')multi=minesMulti(r);if(r.game==='aviator')multi=action!=='recover'&&body.multiplier>0&&value<r.result.crash?Math.min(value,200):0;
return reply(await rpc('bet_settle',{p_user:id,p_round:r.id,p_multi:multi}));}
if(action==='challenge'){if(!allowed.includes(body.game)||body.receiver===id||!/^[0-9a-f-]{36}$/i.test(body.receiver||''))throw Error('Desafio inválido');await db('bet_challenges','POST',{sender:id,receiver:body.receiver,game:body.game});return reply({ok:true});}
if(action==='challenge/accept'){if(!/^[0-9a-f-]{36}$/i.test(body.id||''))throw Error('Desafio inválido');const rows=await db('bet_challenges?id=eq.'+body.id+'&receiver=eq.'+id+'&status=eq.pending','PATCH',{status:'accepted'});if(!rows.length)throw Error('Desafio indisponível');return reply({ok:true});}return reply({error:'Ação desconhecida'},404);
}catch(e){return reply({error:e instanceof Error?e.message:'Falha no serviço'},400);}});

