const arcadeGames=['plinko','mecha','sahur','fishing'];
for(const g of [['mecha','scan-face','Mecha Chameleon','Encontre figuras escondidas nas pinturas','0px'],['sahur','drum','Tung Tung Sahur','Um slot iluminado pela madrugada','0px'],['fishing','fish','Pesca do GB','Lance a linha e recolha na hora certa','0px']]){games.push(g);items.push(g.slice(0,3));iconNames[g[0]]=g[1];}
groups.push({id:'aventuras',title:'Aventuras',icon:'compass',games:['mecha','sahur','fishing']});items.push(['aventuras','compass','Aventuras']);iconNames.aventuras='compass';
let arcadeWorld=null,arcadeRound=null,arcadeRequest=false,arcadeFrame=0,arcadeClock=0;
const arcadeLabels={plinko:'Plinko 3D',mecha:'Mecha Chameleon',sahur:'Tung Tung Sahur',fishing:'Pesca do GB'};
const arcadeRules={plinko:'A aposta é dividida entre as bolas. Com 2 bolas, o retorno recebe fator 0,90; com 3, fator 0,80. Cada pote mostra seu multiplicador.',mecha:'Encontre 8 camuflados. Cada acerto aumenta o retorno. Dois tiros no vazio perdem a aposta. Você tem 60 segundos e pode recolher antes.',sahur:'Bata quando o marcador estiver na faixa verde. Acerte 8 compassos. Dois erros perdem a aposta. Recolha quando quiser.',fishing:'Lance sua linha. Quando a boia afundar e o aviso aparecer, recolha em até 1,25 segundo. Puxar cedo ou tarde perde a aposta.'};
function arcadeStop(){cancelAnimationFrame(arcadeFrame);arcadeWorld?.dispose();arcadeWorld=null;}
function arcadeNow(){return Date.now()+arcadeClock;}
function arcadeMarkup(g){if(g==='sahur'||g==='fishing')return arcadeArtMarkup(g);return `<section class="arcade-page ${g}"><div class="arcade-title"><div><h1>${arcadeLabels[g]}</h1><p>${g==='mecha'?'Olhe duas vezes. Eles estão por aqui.':g==='sahur'?'A madrugada tem seu próprio ritmo.':g==='fishing'?'Um lago, uma linha e o momento certo.':'Uma queda. Até três bolas. Nove destinos.'}</p></div><span>Saldo fictício · sem dinheiro real</span></div><div class="arcade-layout"><section class="arcade-stage"><div id="arcade-world" tabindex="0" aria-label="${g==='mecha'?'Pintura 2D com figuras camufladas. Use o zoom e arraste para explorar. Clique para atirar.':'Cenário 3D do jogo'}"></div><div class="arcade-hud"><span id="arcade-count">${g==='mecha'?'0 / 8 encontrados':g==='sahur'?'0 / 8 compassos':g==='plinko'?'1 bola':'Linha recolhida'}</span><b id="arcade-value">0,00×</b><span id="arcade-misses">${['mecha','sahur'].includes(g)?'0 / 2 erros':''}</span></div>${g==='sahur'?'<div class="sahur-timing"><div class="sahur-zone"></div><i id="sahur-marker"></i></div>':''}<div id="arcade-feedback" role="status">${g==='mecha'?'Explore a pintura com o zoom. Dois cliques no vazio perdem a aposta.':'Escolha a aposta para começar.'}</div></section><aside class="arcade-controls"><div class="arcade-wallet"><small>Seu saldo fictício</small><b id="game-balance">${money(state.balance)}</b></div><label for="bet">Valor da aposta<input id="bet" type="number" min="1" step="1" value="5" inputmode="decimal"></label><div class="arcade-quick">${[5,10,25,50].map(n=>`<button class="subtle" data-arcade-bet="${n}">${n}</button>`).join('')}</div>${g==='plinko'?'<label for="plinko-balls">Quantidade de bolas<select id="plinko-balls"><option value="1">1 bola · retorno integral</option><option value="2">2 bolas · fator 0,90</option><option value="3">3 bolas · fator 0,80</option></select></label>':''}<button id="play" class="primary">${g==='plinko'?'Soltar bolas':g==='fishing'?'Lançar linha':'Começar'}</button>${g==='sahur'?'<button id="arcade-hit" class="arcade-drum" disabled>BATER · ESPAÇO</button>':''}${g==='fishing'?'<button id="arcade-reel" class="primary" disabled>Recolher linha</button>':''}${['mecha','sahur'].includes(g)?'<button id="arcade-bank" class="subtle" disabled>Recolher retorno</button>':''}<p class="arcade-rules">${arcadeRules[g]}</p><a href="#amigos" class="subtle">Jogar com a turma</a></aside></div><div id="arcade-history">${summaryMarkup(g)}</div></section>`;}
const arcadeBeforeRender=render,arcadeBeforeStart=start;mountPlinko=()=>{};
render=function(){arcadeStop();if(!arcadeGames.includes(page)){arcadeBeforeRender();return;}disposeScene();cleanupPhysics();document.body.classList.remove('pm-focus','mateo-focus');$('#mateo-close')?.remove();$('#mateo-focus-music')?.remove();nav();$('#main').innerHTML=arcadeMarkup(page);musicButton();music();photos();lucide.createIcons();$('#play').onclick=arcadeStart;$('#bet').addEventListener('input',()=>{if($('#art-stake'))$('#art-stake').textContent=money(Number($('#bet').value)||0);});$('#arcade-bank')?.addEventListener('click',arcadeBank);$('#arcade-hit')?.addEventListener('click',()=>arcadeHit(-1));$('#arcade-reel')?.addEventListener('click',arcadeBank);document.querySelectorAll('[data-arcade-bet]').forEach(b=>b.onclick=()=>{if(!busy){$('#bet').value=b.dataset.arcadeBet;if($('#art-stake'))$('#art-stake').textContent=money(Number($('#bet').value));}});$('#plinko-balls')?.addEventListener('change',()=>$('#arcade-count').textContent=$('#plinko-balls').value+' bola(s)');try{arcadeWorld=page==='plinko'?arcadeScene(page):arcadeArtScene(page);if(page==='mecha')arcadeWorld.map(arcadeOutcome('mecha',345));if(page==='sahur')arcadeWorld.drum();sahurBind();if(page==='fishing')arcadeWorld.lake();if(page==='plinko')arcadeWorld.board();}catch(e){$('#arcade-feedback').textContent=page==='plinko'?'O 3D não iniciou. Ative a aceleração gráfica do navegador e recarregue.':'O cenário não carregou. Recarregue antes de apostar.';$('#play').disabled=true;console.warn(e);}if(!reduced())$('#main').animate([{opacity:.4,transform:'translateY(14px)'},{opacity:1,transform:'none'}],{duration:500,easing:'cubic-bezier(.16,1,.3,1)'});};
start=function(){return arcadeGames.includes(page)?arcadeStart():arcadeBeforeStart();};
function arcadeControl(){const active=!!arcadeRound;$('#play').disabled=active||arcadeRequest;$('#bet').disabled=active;document.querySelectorAll('[data-arcade-bet]').forEach(b=>b.disabled=active);if($('#plinko-balls'))$('#plinko-balls').disabled=active;if($('#arcade-bank'))$('#arcade-bank').disabled=!active||arcadeRequest||!(arcadeRound.found?.length);if($('#arcade-hit'))$('#arcade-hit').disabled=!active||arcadeRequest;if($('#arcade-reel'))$('#arcade-reel').disabled=!active||arcadeRequest;}
async function arcadeStart(){if(!shared)return betEntry();if(busy||serverPending||arcadeRequest||serverRound||!arcadeWorld)return;if(arcadeWorld.ready&&!arcadeWorld.ready()){toast('Espere a pintura carregar antes de começar.');return;}if(window.betSocial?.engine<3||!window.betSocial?.engine){toast('Atualize a função bet-api com o novo arquivo para liberar os jogos.');sahurAuto=0;return;}const n=wager();if(n===null){$('#arcade-feedback').textContent='Escolha uma aposta a partir de R$ 1, dentro do seu saldo fictício.';sahurAuto=0;return;}arcadeSound('start');arcadeRequest=true;serverPending=true;arcadeControl();const g=page;try{const t0=Date.now(),data=await api('round',{game:g,bet:Math.round(n*100),balls:Number($('#plinko-balls')?.value||1)});arcadeClock=data.serverTime-(t0+Date.now())/2;serverRound={id:data.id};arcadeRound={id:data.id,game:g,bet:n,created:Date.parse(data.created),found:[],misses:0,...data.arcade};state.balance=data.balance/100;stake=n;busy=true;updateBalance();$('#game-balance').textContent=money(state.balance);$('#arcade-value').textContent='0,00×';$('#arcade-misses').textContent=['mecha','sahur'].includes(g)?'0 / 2 erros':'';
 if(g==='plinko'){const result=data.arcade;if(!result?.paths)throw Error('Atualize a função bet-api antes de jogar.');$('#arcade-feedback').textContent='Acompanhe as bolas até os potes.';arcadeWorld.drop(result.paths,async()=>{try{await arcadeBank();}catch{}});}
 if(g==='mecha'){arcadeWorld.map(data.arcade);$('#arcade-feedback').textContent='Rodada iniciada. Dois tiros no vazio encerram a caçada.';}
 if(g==='sahur'){ $('#arcade-feedback').textContent='Os tambores estão girando…';arcadeWorld.spin(data.arcade,arcadeBank); }
 if(g==='fishing'){arcadeWorld.cast(true);$('#arcade-feedback').textContent='A linha está na água… espere a boia.';}
 }catch(e){toast(e.message);$('#arcade-feedback').textContent=e.message;}finally{arcadeRequest=false;serverPending=false;arcadeControl();}}
async function arcadeComplete(data,text){$('#arcade-retry')?.remove();arcadeWorld?.result?.(data,arcadeRound);serverRound=null;arcadeRound=null;busy=false;serverPending=false;state.balance=(data.balance??Math.round(state.balance*100))/100;updateBalance();arcadeControl();$('#arcade-feedback').textContent=text;$('#arcade-value').textContent=Number(data.multiplier??data.multi??0).toFixed(2)+'×';await synchronize();$('#game-balance').textContent=money(state.balance);$('#arcade-history').innerHTML=summaryMarkup(page);arcadeLove();if(page==='sahur')sahurAfterRound();}
async function arcadeBank(){if(!arcadeRound||arcadeRequest)return;arcadeRequest=true;serverPending=true;arcadeControl();const r=arcadeRound;try{const data=await api('settle',{round:r.id,multiplier:1});arcadeWorld?.cast(false);await arcadeComplete(data,data.payout?'Retorno: '+money(data.payout/100)+' fictícios.':'Sem retorno desta vez.');}catch(e){toast(e.message);$('#arcade-feedback').textContent='Falha ao sincronizar. Seu resultado fica salvo no servidor.';if(!$('#arcade-retry')){const b=document.createElement('button');b.id='arcade-retry';b.className='primary';b.textContent='Tentar sincronizar';b.onclick=arcadeBank;$('.arcade-controls').append(b);}}finally{arcadeRequest=false;serverPending=false;arcadeControl();}}
async function arcadeHit(target){if(!arcadeRound||arcadeRequest||page!=='mecha')return;arcadeRequest=true;arcadeControl();try{const data=await api('arcade/hit',{round:arcadeRound.id,target,at:arcadeNow()});if(data.duplicate){$('#arcade-feedback').textContent='Esse camuflado já foi encontrado.';return;}const p=data.progress||{};arcadeRound.found=p.found||[];arcadeRound.misses=p.misses||0;if(data.hit){if(page==='mecha')arcadeWorld.found(target);else arcadeWorld.beat();}$('#arcade-count').textContent=arcadeRound.found.length+' / 8 '+(page==='mecha'?'encontrados':'compassos');$('#arcade-misses').textContent=arcadeRound.misses+' / 2 erros';$('#arcade-value').textContent=Number(data.multi||0).toFixed(2)+'×';$('#arcade-feedback').textContent=data.hit?'Acertou! Continue ou recolha seu retorno.':'Errou. Mais um tiro no vazio encerra a rodada.';if(data.ended)await arcadeComplete(data,data.payout?'Desafio completo! '+money(data.payout/100)+' fictícios.':'Dois erros. A aposta foi perdida.');}catch(e){toast(e.message);}finally{arcadeRequest=false;arcadeControl();}}
window.addEventListener('keydown',e=>{if(false&&page==='sahur'&&e.code==='Space'&&!['INPUT','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();arcadeHit(-1);}});
const beforeArcadeApply=betApply;betApply=function(data){beforeArcadeApply(data);window.betSocial.engine=data.engine||1;window.betSocial.pending=data.pending||[];if(!busy)arcadeLove();};
function arcadeLove(){if(!shared||state.balance!==0||busy||serverPending||window.betSocial?.pending?.length||window.betSocial?.duels.some(d=>d.status==='active')||$('#gb-love'))return;const root=document.createElement('section');root.id='gb-love';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','GB te ama');root.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();root.querySelector('button').focus();}});root.innerHTML='<div><span class="gb-heart">'+icon('heart-handshake')+'</span><h2>GB te ama.</h2><p>O saldo zerou, mas a brincadeira continua.</p><b>+ R$ 30,00</b><small>Saldo fictício · sem dinheiro real</small><button class="primary">Receber meu abraço</button></div>';document.body.append(root);lucide.createIcons();const b=root.querySelector('button');b.focus();b.onclick=async()=>{b.disabled=true;try{await api('love');root.remove();await synchronize();render();toast('R$ 30 fictícios para continuar jogando.');}catch(e){toast(e.message);b.disabled=false;}};}
setInterval(arcadeLove,750);
let arcadeAudio=null;
function arcadeSound(kind){if(!state.music||document.hidden)return;try{if(!arcadeAudio)arcadeAudio=new(window.AudioContext||window.webkitAudioContext)();arcadeAudio.resume().catch(()=>{});const c=arcadeAudio,t=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type=kind==='drum'?'sine':'triangle';o.frequency.setValueAtTime(kind==='drum'?170:kind==='bite'?700:380,t);o.frequency.exponentialRampToValueAtTime(kind==='drum'?55:kind==='bite'?1200:160,t+.15);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.12,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+.26);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.28);}catch{}}

render();

