function arcadeScene(game){const T=window.THREE;if(!T)throw Error('WebGL indisponível');const host=$('#arcade-world'),renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(game==='mecha'?0x111e26:game==='fishing'?0x072738:0x0c1021);host.append(renderer.domElement);const scene=new T.Scene,camera=new T.PerspectiveCamera(42,1,.1,250);camera.position.set(0,18,42);camera.lookAt(0,10,0);scene.add(new T.HemisphereLight(0xd6efff,0x152830,2));const key=new T.DirectionalLight(0xffe5b4,3);key.position.set(10,25,18);scene.add(key);const rim=new T.PointLight(game==='mecha'?0x37d4b0:0x678bff,90,65);rim.position.set(-12,13,0);scene.add(rim);
 let running=true,time=0,last=performance.now(),drop=null,casting=false,angle=.65,elevation=.8,distance=32,drumBody=null;const balls=[],pins=[],pots=[],targets=new Map(),materials=[],textures=[],mapRoot=new T.Group,lakeRoot=new T.Group,boardRoot=new T.Group;scene.add(mapRoot,lakeRoot,boardRoot);const ray=new T.Raycaster,mouse=new T.Vector2;
 function material(color,metal=.2){const m=new T.MeshStandardMaterial({color,metalness:metal,roughness:.48});materials.push(m);return m;}
 const gold=material(0xffc66d,.8),steel=material(0x8bb3c4,.8),ink=material(0x101b2c,.4),wood=material(0x996437,.1),white=material(0xdde6de,.45),jade=material(0x238f78,.4),ground=material(0x344850),water=material(0x127f96,.75);
 function mesh(g,m,x=0,y=0,z=0,parent=scene){const o=new T.Mesh(g,m);o.position.set(x,y,z);parent.add(o);return o;}
 function box(x,y,z,w,h,d,m,parent=scene){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent);}
 function sphere(x,y,z,r,m,parent=scene){return mesh(new T.SphereGeometry(r,12,10),m,x,y,z,parent);}
 function label(text,x,y,z,parent=scene){const c=document.createElement('canvas');c.width=256;c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='#0c1322';ctx.fillRect(0,0,256,100);ctx.fillStyle='#ffe2a3';ctx.font='bold 48px Segoe UI';ctx.textAlign='center';ctx.fillText(text,128,66);const texture=new T.CanvasTexture(c);textures.push(texture);const m=new T.MeshBasicMaterial({map:texture,transparent:true});materials.push(m);const o=mesh(new T.PlaneGeometry(2.8,1.1),m,x,y,z,parent);return o;}
 function clear(group){while(group.children.length){const c=group.children[0];c.traverse(o=>o.geometry?.dispose());group.remove(c);}}
 function board(){camera.position.set(0,17,44);camera.lookAt(0,13,0);box(0,13,-1,32,29,.8,ink,boardRoot);box(-16,13,0,.5,29,1,gold,boardRoot);box(16,13,0,.5,29,1,gold,boardRoot);for(let row=0;row<8;row++)for(let col=0;col<=row;col++){const o=mesh(new T.CylinderGeometry(.22,.22,.8,10),steel,(col-row/2)*3.4,25-row*3,0,boardRoot);o.rotation.x=Math.PI/2;pins.push(o);}
 arcadePots.forEach((v,i)=>{const x=(i-4)*3.4;const body=mesh(new T.CylinderGeometry(1.45,1.25,2,24,1,true),i===4?jade:gold,x,.7,0,boardRoot);mesh(new T.TorusGeometry(1.43,.12,8,24),gold,x,1.7,0,boardRoot).rotation.x=Math.PI/2;mesh(new T.CylinderGeometry(1.25,1.25,.1,24),ink,x,.1,0,boardRoot);label(v+'×',x,-.5,1.5,boardRoot);pots.push(body);});label('PLINKO',0,29.8,0,boardRoot);}
 function dropBalls(paths,done){balls.forEach(b=>{boardRoot.remove(b);b.geometry.dispose();});balls.length=0;paths.forEach((p,i)=>{const b=sphere(0,28,1,.46,i===0?gold:i===1?white:jade,boardRoot);b.userData={path:p,index:i};balls.push(b);});drop={start:performance.now(),done,fired:false};}
 function mannequin(t){const group=new T.Group;group.userData.target=t.id;mapRoot.add(group);group.position.set(t.x,0,t.z);const torso=mesh(new T.CylinderGeometry(.26,.34,.85,10),white,0,.95,0,group);sphere(0,1.6,0,.26,white,group);box(0,1.63,.24,.27,.07,.035,jade,group);for(const side of [-1,1]){const leg=mesh(new T.CylinderGeometry(.105,.13,.75,8),white,side*.16,.35,0,group);const arm=mesh(new T.CylinderGeometry(.08,.12,.68,8),white,side*.43,1,0,group);arm.rotation.z=side*(t.pose===1?2.2:t.pose===2?1.45:.4);sphere(side*.16,.06,.1,.12,white,group);}if(t.pose===3){group.rotation.x=Math.PI/2;group.position.y=.35;}if(t.pose===2)group.rotation.z=.12;targets.set(t.id,group);return group;}
 function map(ts){clear(mapRoot);targets.clear();scene.fog=new T.Fog(0x111e26,35,75);mesh(new T.CylinderGeometry(17,19,1.5,32),ground,0,-1,0,mapRoot);for(let i=0;i<16;i++){const a=i*Math.PI*2/16;const x=Math.cos(a)*15,z=Math.sin(a)*15;box(x,1.2,z,2.1,3.1,2.1,ink,mapRoot);sphere(x+.5,3,z,.6,jade,mapRoot);}for(let i=0;i<6;i++)box((i-2.5)*4,0.02,0,3.8,.05,1.4,steel,mapRoot);ts.forEach(t=>{mannequin(t);box(t.x+1,.55,t.z+.55,1.15,1.1,1.1,wood,mapRoot);box(t.x-1,1,t.z-1.1,.6,2.6,1.8,ink,mapRoot);});mapCamera();}
 function mapCamera(){camera.position.set(Math.sin(angle)*distance,Math.sin(elevation)*distance,Math.cos(angle)*distance);camera.lookAt(0,0,0);}
 function found(id){const o=targets.get(id);if(o){o.traverse(m=>{if(m.isMesh)m.material=jade;});o.userData.found=true;}}
 function drum(){camera.position.set(0,8,17);camera.lookAt(0,3,0);box(0,-.5,0,18,1,12,ink,mapRoot);drumBody=new T.Group;mapRoot.add(drumBody);const body=mesh(new T.CylinderGeometry(.8,.8,4,24),wood,0,3,0,drumBody);sphere(-.24,3.85,.73,.13,ink,drumBody);sphere(.24,3.85,.73,.13,ink,drumBody);box(0,3.45,.76,.35,.07,.035,white,drumBody);for(const s of [-1,1]){box(s*.35,.6,0,.25,1.4,.3,wood,drumBody);const arm=box(s*1,2.3,0,.25,1.8,.28,wood,drumBody);arm.rotation.z=-s*.45;}const bat=mesh(new T.CylinderGeometry(.12,.22,2,12),wood,1.7,2.6,0,drumBody);bat.rotation.z=-.5;mesh(new T.CylinderGeometry(1.5,1.3,1.4,24),gold,0,.3,2.5,mapRoot);mesh(new T.CylinderGeometry(1.42,1.42,.1,24),white,0,1.05,2.5,mapRoot);label('TUNG TUNG',0,6.5,0,mapRoot);for(let i=0;i<7;i++){box((i-3)*2.5,1,-4,.15,3,.15,wood,mapRoot);sphere((i-3)*2.5,2.8,-4,.2,gold,mapRoot);}}
 function beat(){arcadeSound('drum');if(drumBody)drumBody.userData.beat=performance.now();}
 function lake(){camera.position.set(0,10,20);camera.lookAt(0,0,0);mesh(new T.CylinderGeometry(13,13,.5,48),water,0,-.5,0,lakeRoot);box(0,-.5,9,7,.8,6,wood,lakeRoot);for(let i=0;i<14;i++){const a=i/14*Math.PI*2,x=Math.cos(a)*12,z=Math.sin(a)*12;mesh(new T.CylinderGeometry(.2,.4,4,8),wood,x,1.5,z,lakeRoot);mesh(new T.ConeGeometry(1.7,4,8),jade,x,4,z,lakeRoot);}const rod=mesh(new T.CylinderGeometry(.045,.12,7,8),wood,1,1,6,lakeRoot);rod.rotation.z=-.55;for(let i=0;i<7;i++){const f=new T.Group;const b=sphere(0,0,0,.45,i%2?gold:steel,f);b.scale.set(1.7,.5,.7);const tail=mesh(new T.ConeGeometry(.4,.6,3),jade,-.85,0,0,f);tail.rotation.z=Math.PI/2;f.position.set((i-3)*2,-.3,Math.sin(i)*4);lakeRoot.add(f);f.userData.fish=i;}}
 let float=null,ripple=null;function cast(active){if(!lakeRoot.children.length)return;casting=active;if(active){lakeRoot.userData.bitePlayed=false;}if(active){if(!float){float=sphere(0,.12,1,.22,gold,lakeRoot);ripple=mesh(new T.TorusGeometry(.8,.02,6,32),white,0,0,1,lakeRoot);ripple.rotation.x=Math.PI/2;}float.visible=true;ripple.visible=true;}else{if(float)float.visible=false;if(ripple)ripple.visible=false;}}
 function shot(event){if(game!=='mecha'||!arcadeRound||arcadeRequest)return;const rect=renderer.domElement.getBoundingClientRect();mouse.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(mapRoot.children,true)[0];let o=hit?.object;while(o&&o.userData.target===undefined)o=o.parent;arcadeHit(o?.userData.target??-1);}
 let pointer=null;renderer.domElement.addEventListener('pointerdown',e=>{if(game==='mecha'){pointer={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};renderer.domElement.setPointerCapture(e.pointerId);}});renderer.domElement.addEventListener('pointermove',e=>{if(!pointer)return;if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>8)pointer.moved=true;if(pointer.moved){angle-=(e.clientX-pointer.lastX)*.006;elevation=Math.max(.45,Math.min(1.2,elevation+(e.clientY-pointer.lastY)*.004));mapCamera();}pointer.lastX=e.clientX;pointer.lastY=e.clientY;});renderer.domElement.addEventListener('pointerup',e=>{if(pointer&&!pointer.moved)shot(e);pointer=null;});renderer.domElement.addEventListener('pointercancel',()=>pointer=null);host.addEventListener('keydown',e=>{if(game!=='mecha')return;if(e.key==='ArrowLeft')angle-=.15;else if(e.key==='ArrowRight')angle+=.15;else if(e.key==='ArrowUp')elevation=Math.min(1.2,elevation+.1);else if(e.key==='ArrowDown')elevation=Math.max(.45,elevation-.1);else return;e.preventDefault();mapCamera();});
 const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;if(game==='plinko'){camera.position.z=Math.max(44,48/camera.aspect);camera.lookAt(0,13,0);}camera.updateProjectionMatrix();});resize.observe(host);
 function tick(now){if(!running)return;arcadeFrame=requestAnimationFrame(tick);if(document.hidden)return;const dt=Math.min((now-last)/1000,.05);last=now;time+=dt;
 if(drop&&!drop.fired){let finished=0;balls.forEach((b,i)=>{const age=(now-drop.start-i*230)/1000;if(age<0)return;const p=b.userData.path;const row=Math.min(7,Math.floor(age/.33)),f=Math.min(1,(age-row*.33)/.33),before=p.slice(0,row).reduce((a,v)=>a+v,0);if(age<8*.33){const x=(before-row/2)*3.4,to=x+(p[row]?1:-1)*1.7;b.position.set(x+(to-x)*f,25-row*3-3*f+Math.sin(f*Math.PI)*.55,1);}else{const bin=p.reduce((a,v)=>a+v,0),fall=Math.min(1,(age-8*.33)/.6);b.position.set((bin-4)*3.4,1.6-fall*.9,0);if(fall>=1)finished++;}});if(finished===balls.length){drop.fired=true;drop.done();}}
 if(drumBody){drumBody.rotation.y=Math.sin(time*.8)*.06;const pulse=drumBody.userData.beat?Math.max(0,1-(now-drumBody.userData.beat)/280):0;drumBody.scale.set(1+pulse*.04,1-pulse*.1,1+pulse*.04);}
 if(game==='fishing'){lakeRoot.children.filter(o=>o.userData.fish!==undefined).forEach(o=>{o.position.x+=Math.sin(time*.5+o.userData.fish)*.003;o.rotation.y=Math.sin(time*.4+o.userData.fish)*.3;});if(float&&casting){const age=arcadeRound?(arcadeNow()-arcadeRound.created)/1000:0,bite=arcadeRound&&age>=arcadeRound.bite&&age<=arcadeRound.bite+arcadeRound.window;if(bite&&!lakeRoot.userData.bitePlayed){lakeRoot.userData.bitePlayed=true;arcadeSound('bite');}float.position.y=bite?-.16+Math.sin(time*20)*.06:.12+Math.sin(time*3)*.035;ripple.scale.setScalar(1+(time%1.5)*.4);if(arcadeRound)$('#arcade-feedback').textContent=bite?'MORDEU! Recolha a linha agora.':age>arcadeRound.bite+arcadeRound.window?'O peixe escapou…':'A linha está na água…';if(arcadeRound&&age>arcadeRound.bite+arcadeRound.window+.5&&!arcadeRequest)arcadeBank();}}
 if(arcadeRound&&['mecha','sahur'].includes(game)){const age=(arcadeNow()-arcadeRound.created)/1000;if(game==='sahur'&&$('#sahur-marker'))$('#sahur-marker').style.left=((age/1.5)%1*100)+'%';if(age>=60&&!arcadeRequest)arcadeHit(-1);}
 renderer.render(scene,camera);
 }arcadeFrame=requestAnimationFrame(tick);
 return{scene,camera,board,drop:dropBalls,map,found,drum,beat,lake,cast,dispose(){running=false;cancelAnimationFrame(arcadeFrame);resize.disconnect();scene.traverse(o=>o.geometry?.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove();}};
}

