// Live duels: every debit, result, deadline and transfer is verified by Supabase.
let duelClockOffset=0,duelView=null,duelRequest=false,duelPolling=false,socialPolling=false;
const socialNames={verite:'Verity',mateo:'Mateo',pirate:'Pedro Moura Blox Fruits'};
const socialRender=render;
function socialName(id){return sharedFriends.find(f=>f.id===id)?.name||'Amigo';}
function socialBonusLabel(){const next=Date.parse(window.betSocial?.bonusAt||'')+1800000,left=Math.max(0,next-Date.now());return left?'Resgate em '+Math.ceil(left/60000)+' min':'+ R$ 500 fictícios';}
async function socialAction(action,body){try{return await api(action,body);}catch(e){toast(e.message);throw e;}}
function socialFriends(){const data=window.betSocial;if(!data)return;const list=data.duels.filter(d=>d.status==='pending'&&Date.parse(d.created)>Date.now()-600000);
 if(!data.bonusAt){$('#main').innerHTML=heading('X1 chegando à turma.')+'<section class="social-intro"><p>O administrador precisa ativar a atualização no Supabase para liberar os duelos e o novo saldo fictício.</p></section>';return;}
 $('#main').innerHTML=heading('Desafie sua turma.','X1 AO VIVO')+`<section class="social-intro"><div><h2>30 segundos. Dois jogadores.</h2><p>Mesmo jogo, aposta de R$ 5 e até 15 giros. Quem fizer o maior lucro vence e recebe o lucro positivo do adversário. Empate ou perdedor sem lucro: nenhuma transferência.</p><small>Saldo fictício · Sem dinheiro real</small></div><div><button class="primary" id="social-bonus">${socialBonusLabel()}</button><p>+ R$ 500 a cada 30 minutos</p></div></section><section class="social-invites">${list.map(d=>`<article><b>${safe(socialName(d.sender===data.userId?d.receiver:d.sender))}</b><span>${socialNames[d.game]} · ${d.receiver===data.userId?'te convidou':'aguardando resposta'}</span>${d.receiver===data.userId?`<button class="primary" data-accept="${d.id}">Aceitar x1</button>`:''}<button class="subtle" data-decline="${d.id}">${d.receiver===data.userId?'Recusar':'Cancelar'}</button></article>`).join('')}</section><div class="social-roster">${sharedFriends.filter(f=>!f.you).map(f=>`<article><div class="avatar">${f.photo?`<img src="${safe(f.photo)}" alt="">`:'😊'}</div><h2>${safe(f.name)}</h2><span>${money(f.balance)} fictícios</span><label>Jogo do x1<select id="duel-game-${f.id}"><option value="verite">Verity</option><option value="mateo">Mateo</option><option value="pirate">Pedro Moura</option></select></label><button class="primary" data-invite="${f.id}">Convidar para x1</button></article>`).join('')||'<p>Seus amigos aparecem aqui depois que entrarem pelo link do site.</p>'}</div>`;
 $('#social-bonus').onclick=socialClaim;
 document.querySelectorAll('[data-invite]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await socialAction('duel/invite',{receiver:b.dataset.invite,game:$('#duel-game-'+b.dataset.invite).value});await synchronize();toast('Convite enviado!');}catch{}finally{b.disabled=false;}});
 document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{duelView=await socialAction('duel/accept',{id:b.dataset.accept});duelClockOffset=(duelView.serverTime||Date.now())-Date.now();render();}catch{b.disabled=false;}});
 document.querySelectorAll('[data-decline]').forEach(b=>b.onclick=async()=>{try{await socialAction('duel/decline',{id:b.dataset.decline});await synchronize();}catch{}});
}
async function socialClaim(){try{await socialAction('bonus',{});await synchronize();toast('R$ 500 fictícios adicionados ao saldo.');}catch{}}
function duelSymbols(game,grid){grid=grid||Array.from({length:5},()=>['gem','bell','crown']);return grid.map(col=>'<div>'+col.map(s=>`<div class="duel-cell">${game==='verite'?reelSymbol(s):game==='mateo'?mateoSymbol(s):pirateSymbol(s)}</div>`).join('')+'</div>').join('');}
function duelArena(){const d=duelView,u=window.betSocial.userId,other=d.sender===u?d.receiver:d.sender;
 $('#main').innerHTML=`<section class="duel-arena"><div class="duel-heading"><div><small>X1 · ${socialNames[d.game]} · saldo fictício</small><h1>Uma rodada contra a turma.</h1></div><strong id="duel-clock">30s</strong></div><div class="duel-split">${[u,other].map((id,i)=>`<article class="duel-player ${i?'opponent':'you'}"><div class="duel-player-title"><h2>${safe(socialName(id))} ${i?'':'<small>Você</small>'}</h2><b id="duel-net-${i}">R$ 0,00</b></div><div id="duel-grid-${i}" class="duel-grid">${duelSymbols(d.game)}</div><div class="duel-player-footer"><span id="duel-count-${i}">0 / 15 giros</span><span id="duel-last-${i}">Aposta: R$ 5</span></div></article>`).join('')}</div><div class="duel-bottom"><button id="duel-spin" class="primary">Girar · R$ 5 fictícios</button><p id="duel-status">Aguardando início…</p><small>30 segundos · um giro a cada 1,5 segundo · lucro = retornos − apostas</small><button id="duel-back" class="subtle" hidden>Voltar aos amigos</button></div></section>`;
 $('#duel-spin').onclick=async()=>{if(duelRequest)return;duelRequest=true;$('#duel-spin').disabled=true;try{const grid=$('#duel-grid-0');grid.classList.add('rolling');duelView=await socialAction('duel/spin',{id:d.id});duelClockOffset=(duelView.serverTime||Date.now())-Date.now();await new Promise(resolve=>setTimeout(resolve,450));grid.classList.remove('rolling');duelUpdate();const snapshot=await api('state');betApply(snapshot);}catch{document.querySelector('.rolling')?.classList.remove('rolling');}finally{duelRequest=false;duelUpdate();}};
 $('#duel-back').onclick=()=>{duelView=null;render();};duelUpdate();
}
function duelUpdate(){if(page!=='amigos'||!$('#duel-clock')||!duelView)return;const d=duelView,u=window.betSocial.userId,other=d.sender===u?d.receiver:d.sender;
 const countdown=Math.ceil((Date.parse(d.started)-(Date.now()+duelClockOffset))/1000),left=Math.max(0,Math.ceil((Date.parse(d.ends)-(Date.now()+duelClockOffset))/1000));$('#duel-clock').textContent=countdown>0?countdown:left+'s';
 [u,other].forEach((id,i)=>{const plays=d.plays?.[id]||[],net=plays.reduce((a,x)=>a+x.payout-500,0);$('#duel-net-'+i).textContent=money(net/100);$('#duel-count-'+i).textContent=plays.length+' / 15 giros';const last=plays.at(-1),el=$('#duel-grid-'+i);if(last&&el.dataset.time!==last.time){el.innerHTML=duelSymbols(d.game,last.grid||last.symbols);el.dataset.time=last.time;$('#duel-last-'+i).textContent='Retorno '+money(last.payout/100);}});
 const mine=d.plays?.[u]||[],last=mine.at(-1);$('#duel-spin').disabled=duelRequest||d.status!=='active'||countdown>0||!left||mine.length>=15||last&&Date.now()+duelClockOffset-Date.parse(last.time)<1600;
 $('#duel-status').textContent=d.status==='finished'?(d.winner?(d.winner===u?'Você venceu! ':'Seu amigo venceu. ')+(d.transfer?'Prêmio: '+money(d.transfer/100)+' fictícios.':'Sem lucro positivo para transferir.'):'Empate. Sem transferência.'):(countdown>0?'Prepare-se…':'Quem terminar com o maior lucro vence.');
 $('#duel-back').hidden=d.status!=='finished';$('#duel-spin').hidden=d.status==='finished';
}
render=function(){socialRender();if(!window.betSocial)return;
 const active=window.betSocial.duels.find(d=>d.status==='active');if(active&&(!duelView||duelView.status==='finished'&&active.id!==duelView.id))duelView=active;
 if(page==='amigos'){if(duelView&&['active','finished'].includes(duelView.status))duelArena();else socialFriends();}
 if($('#bet'))$('#bet').removeAttribute('max');
 ['#mateo-add','#mateo-gift','#mateo-bonus'].forEach(k=>{if($(k))$(k).onclick=socialClaim;});
 if(!$('#social-redeem')){const wallet=$('.top-wallet');if(wallet){const b=document.createElement('button');b.id='social-redeem';b.className='subtle';b.textContent= socialBonusLabel();b.onclick=socialClaim;wallet.after(b);}}
 $('#social-redeem')?.setAttribute('title','Resgatar R$ 500 fictícios a cada 30 minutos');
};
setInterval(async()=>{if($('#social-redeem'))$('#social-redeem').textContent=socialBonusLabel();duelUpdate();if(!shared||duelPolling||!duelView||duelView.status!=='active')return;duelPolling=true;try{const next=await api('duel/status',{id:duelView.id});duelClockOffset=(next.serverTime||Date.now())-Date.now();if(!duelRequest){if(duelView.plays){for(const id of [next.sender,next.receiver])if((duelView.plays[id]||[]).length>(next.plays?.[id]||[]).length){next.plays=next.plays||{};next.plays[id]=duelView.plays[id];}}duelView=next;}duelUpdate();if(next.status==='finished')await synchronize();}catch(e){if(page==='amigos'&&$('#duel-status'))$('#duel-status').textContent='Reconectando ao x1…';}finally{duelPolling=false;}},1000);
setInterval(async()=>{if(!shared||socialPolling||busy||serverPending||duelView?.status==='active'||!(page==='amigos'||window.betSocial?.duels.some(d=>d.status==='pending')))return;socialPolling=true;try{const before=JSON.stringify(window.betSocial?.duels),data=await api('state');betApply(data);if(JSON.stringify(data.duels)!==before){render();if(duelView?.status==='active'&&page!=='amigos')toast('Seu x1 começou! Abra a aba Amigos.');}}catch{}finally{socialPolling=false;}},2000);
render();

