// Layered instruments and mechanical reel sounds; the existing volume button controls all audio.
(function(){
let context,master,noise,ambient,musicTheme=null;const scheduledSources=new Set();function trackSource(source){scheduledSources.add(source);source.onended=()=>scheduledSources.delete(source)}function stopScheduled(){for(const source of scheduledSources){try{source.stop()}catch{}}scheduledSources.clear()}const pirateTrack=new Audio("pedro-sea-theme.mp3");pirateTrack.loop=true;pirateTrack.volume=.32;pirateTrack.preload="metadata";
function engine(){if(!state.music||document.hidden)return null;if(!context){context=new(window.AudioContext||window.webkitAudioContext)();master=context.createGain();master.gain.value=.55;master.connect(context.destination);noise=context.createBuffer(1,context.sampleRate*2,context.sampleRate);const data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;}context.resume().catch(()=>{});return context}
function note(hz,time,length,volume=.08,type='triangle'){const c=engine();if(!c)return;const o=c.createOscillator(),g=c.createGain(),f=c.createBiquadFilter();o.type=type;o.frequency.value=hz;f.type='lowpass';f.frequency.value=1800;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(volume,time+.025);g.gain.exponentialRampToValueAtTime(.0001,time+length);o.connect(f).connect(g).connect(master);trackSource(o);o.start(time);o.stop(time+length+.02)}
function texture(time,length,frequency,volume){const c=engine();if(!c)return;const source=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();source.buffer=noise;source.loop=true;filter.type='bandpass';filter.frequency.value=frequency;filter.Q.value=.7;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(volume,time+.02);g.gain.exponentialRampToValueAtTime(.0001,time+length);source.connect(filter).connect(g).connect(master);trackSource(source);source.start(time);source.stop(time+length+.02)}
function soundtrack(){if(page==='pirate')return;const c=engine();if(!c)return;const now=c.currentTime;const chords=[[130.81,164.81,196],[110,130.81,164.81],[87.31,130.81,174.61],[98,146.83,196]];chords.forEach((chord,i)=>{chord.forEach(h=>note(h,now+i*2,1.9,.021,'sine'));note(chord[0]/2,now+i*2,1.7,.04,'sine');for(let beat=0;beat<4;beat++){const t=now+i*2+beat*.5;texture(t,.075,beat%2?3200:500,.02);note(chord[(beat+i)%3]*4,t+.25,.32,.018)}})}
music=function(){clearInterval(audioClock);clearInterval(ambient);audioClock=null;ambient=null;stopScheduled();pirateTrack.pause();musicTheme=state.music?(page==='pirate'?'pirate':'platform'):null;if(!state.music){if(master)master.gain.setTargetAtTime(.0001,context.currentTime,.03);return}engine();if(master)master.gain.setTargetAtTime(.55,context.currentTime,.04);if(musicTheme==='pirate'){pirateTrack.play().catch(()=>{});return}soundtrack();ambient=setInterval(()=>{if(state.music&&page!=='pirate')soundtrack()},8000);audioClock=ambient};
const priorButton=musicButton;musicButton=function(){priorButton();const b=$('#music-toggle');b.setAttribute('aria-label',state.music?'Silenciar áudio':'Ativar áudio');b.title=state.music?'Silenciar música e efeitos':'Ativar música e efeitos';const old=b.onclick;b.onclick=()=>{old();if(!state.music){musicTheme=null;stopScheduled();pirateTrack.pause();clearInterval(ambient);if(master)master.gain.setTargetAtTime(.0001,context.currentTime,.03)}}};
const priorStart=start;start=function(){const was=busy;priorStart();if(was||!busy)return;const c=engine();if(!c)return;const now=c.currentTime;if(!['verite','mateo','pirate'].includes(page)){if(page==='aviator'){texture(now,1.3,500,.08);[130,196,261].forEach((hz,i)=>note(hz,now+i*.2,.35,.04,'sawtooth'))}else if(page==='double'||page==='bacbo'){for(let i=0;i<10;i++)texture(now+i*.1,.045,1600,.04)}else if(page==='plinko'){for(let i=0;i<7;i++)note(600+i*95,now+i*.13,.12,.04)}return;}texture(now,1.75,750,.10);for(let col=0;col<5;col++){const t=now+1+col*.21;texture(t,.09,2200,.14);note(190+col*35,t,.12,.065,'triangle')}};
const priorFinish=finish;finish=function(game,bet,multi){priorFinish(game,bet,multi);const c=engine();if(!c)return;const now=c.currentTime;if(game==='mines'&&multi===0){texture(now,.65,180,.22);note(55,now,.6,.12,'sawtooth');return;}if(multi>0){const melody=multi>=6?[523.25,659.25,783.99,1046.5,1318.51,1567.98]:[523.25,659.25,783.99];melody.forEach((hz,i)=>{note(hz,now+i*.13,.65,.10);note(hz/2,now+i*.13,.6,.035,'sine')});[261.63,329.63,392].forEach(hz=>note(hz,now+melody.length*.13,1.3,.045,'sine'));if(multi>=6)for(let i=0;i<12;i++)texture(now+.6+i*.075,.08,3500+i*120,.027)}else{texture(now,.15,350,.04)}};
const previousRender=render;render=function(){previousRender();const targetTheme=state.music?(page==='pirate'?'pirate':'platform'):null;if(targetTheme!==musicTheme)music();if(page==='verite'){const text=$('.payline b');if(text)text.textContent='Caminhos ligados desde a esquerda · 3: 2× · 4: 5× · 5: 12× · Maior caminho paga';}musicButton()};render();
})();
