// Public-key client. Balances and payouts are authoritative in the Edge Function.
let betSession=null,betSessionRefresh=null,betSettling=null,betFlightPoll=null,betRevealing=false,betConnecting=false;
try{betSession=JSON.parse(localStorage.getItem('kjub-supabase-session'))}catch{}
const betConfig=window.BET_SUPABASE;
async function betAuth(path,body){const r=await fetch(betConfig.url+'/auth/v1/'+path,{method:'POST',headers:{apikey:betConfig.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.msg||data.message||data.error_description||'Não foi possível entrar.');return data;}
function betStoreSession(data){betSession={...data,expires_at:data.expires_at||Math.floor(Date.now()/1000)+data.expires_in};localStorage.setItem('kjub-supabase-session',JSON.stringify(betSession));}
async function betToken(){if(!betSession)throw Error('Entre como convidado para jogar online.');if(betSession.expires_at*1000<Date.now()+60000){if(!betSessionRefresh)betSessionRefresh=betAuth('token?grant_type=refresh_token',{refresh_token:betSession.refresh_token}).then(betStoreSession).finally(()=>betSessionRefresh=null);await betSessionRefresh;}return betSession.access_token;}
api=async function(action,body={}){const token=await betToken();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(betConfig.url+'/functions/v1/bet-api',{method:'POST',headers:{apikey:betConfig.publishableKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({...body,action}),signal:controller.signal});const data=await r.json();if(!r.ok)throw Error(data.error||data.message||'Backend indisponível.');return data;}catch(e){if(e.name==='AbortError')throw Error('O servidor demorou. Tente sincronizar novamente.');throw e;}finally{clearTimeout(timer);}};
function betApply(data){window.betSocial={userId:data.user.id,bonusAt:data.user.bonus_at,duels:data.duels||[]};state={...state,name:data.user.name,photo:data.user.photo||undefined,balance:data.user.balance/100,wins:data.user.wins,rounds:data.user.rounds,log:data.log.map(l=>({game:l.game,bet:l.bet/100,payout:l.payout/100,multi:Number(l.multiplier),time:l.time}))};sharedFriends=data.friends.map(f=>({...f,face:'😊',balance:f.balance/100,you:f.id===data.user.id}));sharedChallenges=data.challenges;shared=true;updateBalance();if($('#pm-top-money'))$('#pm-top-money').textContent=money(state.balance);}
synchronize=async function(){const data=await api('state');betApply(data);if(!busy&&!serverPending&&!games.some(g=>g[0]===page))render();return data;};
settleShared=function(multiplier){if(!shared||!serverRound)return betSettling; if(betSettling)return betSettling;const round=serverRound;serverPending=true;betSettling=(async()=>{try{const result=await api('settle',{round:round.id,multiplier});serverRound=null;rng=localRng;state.balance=result.balance/100;await synchronize();}catch(e){message('Rodada pendente: '+e.message);toast('Seu resultado permanece no servidor. Recarregue para sincronizar.');throw e;}finally{serverPending=false;betSettling=null;}})();betSettling.catch(()=>{});return betSettling;};
const betLocalStart=start,betLocalReveal=reveal,betLocalCash=cashout,betLocalEnd=endFlight;
// Keep the requested game stable while its server debit is pending.
window.addEventListener('hashchange',e=>{if(serverPending||betRevealing){e.stopImmediatePropagation();history.replaceState(null,'','#'+page);toast('Aguarde a sincronização da rodada.');}},true);
start=async function(){if(!shared){betEntry();return;}if(busy||serverPending||serverRound||betRevealing||betConnecting)return;if(!window.betSocial?.bonusAt){toast("A atualização do Supabase precisa ser ativada pelo administrador.");return;}const n=wager();if(n===null)return;const game=page;serverPending=true;if($('#play'))$('#play').disabled=true;try{const result=await api('round',{game,bet:Math.round(n*100),color,side:bacSide,mines:Number($('#mine-count')?.value||2)});serverRound=result;openedCells=[];state.balance=result.balance/100+n;rng=result.seed===undefined?localRng:seededClient(result.seed);
if(game==='aviator'){let first=true;rng=()=>{if(first){first=false;return .999999;}return localRng();};}
shared=false;try{betLocalStart();}finally{shared=true;}if(game==='mines'&&mines){mines.bombs=new Set();mines.count=result.mines||3;const select=$('#mine-count');if(select&&Number(select.value)!==mines.count){select.innerHTML='<option value="'+mines.count+'">'+mines.count+' minas</option>';}}if(game==='aviator'&&aviatorRound){clearInterval(flightTimer);const roundId=result.id;clearInterval(betFlightPoll);let checking=false;betFlightPoll=setInterval(async()=>{if(checking||!aviatorRound)return;checking=true;try{const status=await api('flight',{round:roundId});if(!aviatorRound)return;flight=status.value;$('.multiplier').textContent=flight.toFixed(2)+'×';if(!aviatorRound.cashed)$('#cash').textContent='Sacar '+money(stake*flight);window.dispatchEvent(new CustomEvent('flight-update',{detail:{value:flight,active:!status.ended}}));if(status.ended){clearInterval(betFlightPoll);aviatorRound.crash=status.value;endFlight();}}catch(e){clearInterval(betFlightPoll);message('Voo sem conexão. Recarregue para recuperar a rodada.');}finally{checking=false;}},250);}
}catch(e){message(e.message);toast(e.message);if($('#play'))$('#play').disabled=false;}finally{serverPending=false;}};
reveal=async function(i){if(!shared)return betLocalReveal(i);if(!busy||!mines||betRevealing||serverPending||!serverRound||mines.open.has(i))return;betRevealing=true;try{const result=await api('reveal',{round:serverRound.id,cell:i});mines.bombs=new Set(result.bombs||[]);betLocalReveal(i);}catch(e){message(e.message);}finally{betRevealing=false;}};
cashout=function(){if(betRevealing||serverPending)return;if(shared&&page==='aviator'){const r=aviatorRound;if(!r||r.cashed)return;serverPending=true;api('settle',{round:serverRound.id,multiplier:flight}).then(async result=>{serverRound=null;flight=Number(result.multiplier||0);r.crash=Math.max(r.crash,flight);shared=false;try{betLocalCash();}finally{shared=true;}serverPending=false;await synchronize();if(!flight)message('O avião saiu antes do saque.');}).catch(e=>{serverPending=false;message(e.message);});return;}betLocalCash();};
endFlight=function(){clearInterval(betFlightPoll);betLocalEnd();};
function betEntry(){if($('#bet-connect-panel'))return;const panel=document.createElement('section');panel.id='bet-connect-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.innerHTML='<form id="bet-connect-form"><img src="logo-kim.png" alt="Kim Jong-un Bet"><h2>Entre para a turma</h2><p>Escolha seu apelido. Sem email ou senha.</p><label>Seu apelido<input id="bet-guest-name" maxlength="24" required autocomplete="nickname" value=""></label><button class="primary" type="submit">Entrar como convidado</button><p id="bet-connect-status" role="status"></p><small>Saldo fictício · Sem dinheiro real<br>Seu acesso fica salvo neste navegador.</small></form>';document.body.append(panel);$('#bet-guest-name').focus();$('#bet-connect-form').onsubmit=async e=>{e.preventDefault();if(betConnecting)return;betConnecting=true;const name=$('#bet-guest-name').value.trim();if(!name){betConnecting=false;return;}const button=panel.querySelector('button');button.disabled=true;$('#bet-connect-status').textContent='Conectando à turma…';try{if(!betSession)betStoreSession(await betAuth('signup',{data:{name}}));await api('recover');await api('profile',{name});await synchronize();panel.remove();render();}catch(error){$('#bet-connect-status').textContent=error.message;button.disabled=false;}finally{betConnecting=false;}};}
async function betConnect(){if(!betSession)return betEntry();betConnecting=true;try{await api('recover');await synchronize();render();}catch(e){toast(e.message);betEntry();}finally{betConnecting=false;}}
setTimeout(betConnect,0);
setInterval(()=>{if(shared&&!busy&&!serverPending&&!betConnecting)synchronize().catch(()=>{});},15000);
